menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Github: https://github.com/elvismacak

# disqus comment
disqus: true
disqus_shortname: lnmpy

# google analytics
# googleTrackId:

# baidu analytics
baiduTrackId: '7c3c55661d86ad294eba178cc74a7d34'

# growingio analytics
growingioTrackId: 'a27aef759ca83c9c'

# sessionstack
# sessionstackId:
